version: 2

updates:
  # Python Backend
  - directory: "/app"
    package-ecosystem: "pip"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[requirements]"

  - directory: "/spoopy-site"
    package-ecosystem: "npm"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[package]"

  - directory: "/"
    package-ecosystem: "github-actions"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "actions"
